version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.2-stretch
    working_directory: /go/src/github.com/Lookyan/jaeger-dependencies
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - run: docker build -t lookyan/jaeger-dependencies:$CIRCLE_BRANCH .
    - run: docker tag lookyan/jaeger-dependencies:$CIRCLE_BRANCH lookyan/jaeger-dependencies:latest
    - run: docker push lookyan/jaeger-dependencies:$CIRCLE_BRANCH
    - run: docker push lookyan/jaeger-dependencies:latest
